const SUPABASE_URL='https://fvuiisuzwezruxmlljty.supabase.co';
const SUPABASE_KEY='sb_publishable_NC5zaQusqVNFdoi3d8s9Ow_5wbtQF1a';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
let user=null,tasks=[],proofs=[],balance=0,currentTask=null;
const $=id=>document.getElementById(id), money=n=>'৳'+Number(n||0).toFixed(2);
function authMsg(t,err=false){$('authMsg').innerHTML=`<div class="auth-error" style="color:${err?'#d33':'#15995a'}">${t}</div>`}
async function boot(){const {data}=await db.auth.getSession();if(data.session){user=data.session.user;await loadApp()}else $('auth').classList.remove('hidden');}
async function loadApp(){ $('auth').classList.add('hidden');$('app').classList.remove('hidden'); await loadData(); render('watch'); }
async function loadData(){
 const [t,p,w,prof]=await Promise.all([
  db.from('watch_tasks').select('*').eq('active',true).order('created_at',{ascending:false}),
  db.from('watch_task_proofs').select('id,reward,completed_at,watch_tasks(title)').eq('user_id',user.id).order('completed_at',{ascending:false}),
  db.from('wallets').select('balance').eq('user_id',user.id).maybeSingle(),
  db.from('profiles').select('full_name,email,referral_code,kyc_status').eq('id',user.id).maybeSingle()
 ]);
 tasks=t.data||[];proofs=p.data||[];balance=w.data?.balance||0;window.profile=prof.data||{};
 $('welcome').textContent='Hi, '+(window.profile.full_name||user.email?.split('@')[0]||'User')+' 👋';$('balance').textContent=money(balance);
}
function render(page){document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));({watch:renderWatch,proofs:renderProofs,discover:renderDiscover,invite:renderInvite,profile:renderProfile}[page])()}
function renderWatch(){ $('content').innerHTML=`<div class="hero"><h2>Watch & Earn 🎬</h2><p>Complete eligible videos and claim the displayed reward.</p></div><div class="section-title"><h3>Available Videos</h3><small>${tasks.length} tasks</small></div>${tasks.map(t=>`<div class="task"><button class="play" onclick="startTask('${t.id}')">▶</button><div class="task-body"><div class="task-head"><strong>Video</strong><span class="reward">+${money(t.reward)}</span></div><p>${escapeHtml(t.title)}</p><div class="meta">📺 ${Math.ceil(t.duration_seconds/60)} min · Verified task</div></div></div>`).join('')||'<div class="card empty">No tasks available right now.</div>'}`}
function renderProofs(){ $('content').innerHTML=`<div class="section-title"><h3>Proofs & History</h3><small>${proofs.length} completed</small></div>${proofs.map(p=>`<div class="task"><div class="play">✓</div><div class="task-body"><div class="task-head"><strong>Video</strong><span class="reward">+${money(p.reward)}</span></div><p>${escapeHtml(p.watch_tasks?.title||'Completed task')}</p><div class="meta">${new Date(p.completed_at).toLocaleString('en-BD')} · Completed</div></div></div>`).join('')||'<div class="card empty">No completed tasks yet.</div>'}`}
function renderDiscover(){ $('content').innerHTML='<div class="hero"><h2>Discover 🔎</h2><p>Explore earning opportunities.</p></div><div class="card"><div class="row"><span>🎬 Video Tasks</span><b class="green">Active</b></div><div class="row"><span>👥 Referral Program</span><b class="green">Active</b></div><div class="row"><span>🏧 Withdrawals</span><b>Coming next</b></div></div>' }
function renderInvite(){const code=window.profile?.referral_code||'WE'+user.id.slice(0,8).toUpperCase();$('content').innerHTML=`<div class="invite-box"><h2>Invite & Earn 👥</h2><p>Share your referral code with friends.</p><div class="invite-code">${code}</div><button class="secondary" onclick="navigator.clipboard?.writeText('${code}');alert('Referral code copied')">Copy Code</button></div>`}
function renderProfile(){const p=window.profile||{};$('content').innerHTML=`<div class="card"><div class="profile-head"><div class="avatar">${(p.full_name||'U')[0].toUpperCase()}</div><div><h2 style="margin:0">${escapeHtml(p.full_name||'User')}</h2><small>${escapeHtml(user.email||'')}</small></div></div></div><div class="card"><div class="row"><span>Wallet balance</span><b class="green">${money(balance)}</b></div><div class="row"><span>Total completed</span><b>${proofs.length}</b></div><div class="row"><span>Verification</span><b class="green">${p.kyc_status||'Account active'}</b></div></div><div class="card"><h3>Withdraw</h3><p style="color:#778583;font-size:13px">bKash / Nagad / USDT withdrawal requests can be submitted after the payment rules and minimum threshold are configured.</p><button class="primary" onclick="withdrawInfo()">Open Withdrawal</button></div><div class="card"><button class="secondary" onclick="signOut()">Logout</button></div>`}
function startTask(id){currentTask=tasks.find(t=>t.id===id);if(!currentTask)return;$('modal').classList.add('show');$('claimBtn').classList.add('hidden');$('modalTitle').textContent='Watching video…';let left=Math.max(5,Math.min(currentTask.duration_seconds,15));$('modalText').textContent=`Keep this screen open (${left}s)`;const timer=setInterval(()=>{left--;$('modalText').textContent=left>0?`Keep this screen open (${left}s)`:'Video completed. Claim your reward.';if(left<=0){clearInterval(timer);$('claimBtn').classList.remove('hidden');$('modalTitle').textContent='Video completed ✓'}},1000)}
$('claimBtn').onclick=async()=>{if(!currentTask)return;$('claimBtn').disabled=true;$('modalText').textContent='Verifying reward…';const {data,error}=await db.functions.invoke('watch-claim-reward',{body:{task_id:currentTask.id}});if(error||data?.error){$('modalText').textContent=data?.error||error.message;$('claimBtn').disabled=false;return} $('modal').classList.remove('show');alert('Reward added: '+money(data.reward));currentTask=null;await loadData();render('watch');$('claimBtn').disabled=false}
$('loginBtn').onclick=async()=>{authMsg('Signing in…');const {data,error}=await db.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(error)return authMsg(error.message,true);user=data.user;await loadApp()};
$('signupBtn').onclick=async()=>{authMsg('Creating account…');const email=$('email').value.trim(),password=$('password').value;if(password.length<6)return authMsg('Password must be at least 6 characters.',true);const {data,error}=await db.auth.signUp({email,password});if(error)return authMsg(error.message,true);if(data.session){user=data.user;await loadApp()}else authMsg('Account created. Check your email to confirm your account.')};
async function signOut(){await db.auth.signOut();location.reload()} function withdrawInfo(){alert('Withdrawal is protected and requires server-side approval/payment integration.')} function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
document.querySelectorAll('.bottom-nav button').forEach(b=>b.onclick=()=>render(b.dataset.page));boot();